apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hsd-oauth-proxy.fullname" . }}
  labels:
    {{- include "hsd-oauth-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hsd-oauth-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hsd-oauth-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: hsd-oauth-proxy-env-cm
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Values.envFromSecret.OAUTH2_PROXY_CLIENT_ID.secretKeyRef.name}}
                  key: {{.Values.envFromSecret.OAUTH2_PROXY_CLIENT_ID.secretKeyRef.key}}
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.envFromSecret.OAUTH2_PROXY_CLIENT_SECRET.secretKeyRef.name}}
                  key: {{.Values.envFromSecret.OAUTH2_PROXY_CLIENT_SECRET.secretKeyRef.key}}
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.envFromSecret.OAUTH2_PROXY_COOKIE_SECRET.secretKeyRef.name}}
                  key: {{.Values.envFromSecret.OAUTH2_PROXY_COOKIE_SECRET.secretKeyRef.key}}
            - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: {{.Values.envFromSecret.OAUTH2_PROXY_REDIS_CONNECTION_URL.secretKeyRef.name}}
                  key: {{.Values.envFromSecret.OAUTH2_PROXY_REDIS_CONNECTION_URL.secretKeyRef.key}}

          {{- range $k, $v := .Values.optionalEnvVariables }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}   
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping #change to /ready for version greater than 7.4.0
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
