name: CI-Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'VERSION'
    - '.bumpversion.cfg'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  HSDP_DOCKER_HOST: docker.na1.hsdp.io

jobs:
  Init:
    runs-on: ubuntu-20.04
    container:
      image: docker.na1.hsdp.io/edi/build-env:master-45
      credentials:
        username: ${{ secrets.HSDP_DOCKER_USER }}
        password: ${{ secrets.HSDP_DOCKER_PASSWORD }}
    outputs:
      branchName: ${{ steps.branch.outputs.branch_name }}
      ciFullImageName: "${{ env.HSDP_DOCKER_HOST }}/edi/edi-foundation-oauth2-proxy:${{ steps.branch.outputs.branch_name }}-${{ github.run_number }}"
      rcFullImageName: "${{ env.HSDP_DOCKER_HOST }}/edi/edi-foundation-oauth2-proxy:${{ steps.branch.outputs.branch_name }}-${{ github.run_number }}-rc"

    steps:
      - uses: actions/checkout@v2
        with:
         token: ${{ secrets.ADMIN_TOKEN }}

      - name: Extract branch name
        uses: vazco/github-actions-branch-name@v1
        id: branch

      - name: Bump version
        if: github.ref == 'refs/heads/main'
        run: |
          bumpversion patch
          new_version=`cat VERSION`
          echo "New version is: $new_version"

          git config --global user.name "CI Build"
          git config --global user.email "ci.build@philips.com"
          git commit -am "Bump version $new_version"
          git push --force

  BlackduckScan:
    needs: [Init]
    runs-on: ubuntu-20.04
    container:
      image: docker.na1.hsdp.io/edi/build-env:master-45
      credentials:
        username: ${{ secrets.HSDP_DOCKER_USER }}
        password: ${{ secrets.HSDP_DOCKER_PASSWORD }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      
      - name: Scan blackduck
        run: |
          pdt blackduck detect \
                --workspace_path ${{ github.workspace }} \
                --project_name 'SA_edifoundation-oauth2proxy' \
                --project_version '1.0' \
                --blackduck_host 'https://blackduck.philips.com' \
                --blackduck_token ${{ secrets.BLACKDUCK_TOKEN }}