name: CI-GATED

on:
  pull_request:
    branches: [ edi-foundation-integration ]
  workflow_dispatch:

jobs:
  Wokflow-Queue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-queue@v1
      
  Gated:
    needs: [Wokflow-Queue]
    runs-on: ubuntu-20.04
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: ${{ secrets.VAULT_HOST }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: true
          secrets: |
            devops/data/github/users/sal-devops token | GITHUB_TOKEN ;
            
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: philips-internal
          repo: hds-auth-gateway
          github_token: ${{ env.GITHUB_TOKEN }}
          workflow_file_name: ci.yaml