name: CI

on:
  push:
    branches:
      - "pics"
    paths-ignore:
      - "docs/**"
      - "VERSION"
      - ".bumpversion.cfg"
      - "**.md"
      - "catalog-info.yaml"
      - "mkdocs.yml"
      - "philips-repo.yaml"

  pull_request:
    branches: [pics]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract branch name
        uses: vazco/github-actions-branch-name@v1
        id: branch

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
        id: go

      - name: Get dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.36.0

      - name: Verify Code Generation
        run: |
          make verify-generate

      - name: Lint
        run: |
          make lint

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

  Build:
    needs: [Tests]
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    outputs:
      oauth2proxyPRTag: ${{ steps.setVariables.outputs.prTag }}
      oauth2proxyCITag: ${{ steps.setVariables.outputs.betaTag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Build Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ${{ github.workspace }}
      #     push: false
      #     tags: ${{ env.DOCKER_REPO }}:${{ github.run_id }}

      # - name: Bump Version
      #   id: bump-version
      #   uses: philips-internal/pics-workflows/.github/actions/bump-version@v2.10
      #   with:
      #     GH_APP_ID: ${{ secrets.REP_GITHUB_APP_ID }}
      #     GH_APP_KEY_BASE64: ${{ secrets.REP_GITHUB_APP_KEY_BASE64 }}

      # - name: Publish Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ${{ github.workspace }}
      #     push: true
      #     tags: ${{ env.DOCKER_REPO }}:${{ steps.bump-version.outputs.version }}
