name: Publish

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-22.04
    name: Publish to docker repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker registry login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PSWD }}
          logout: true

      - name: Publish Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}
          push: true
          tags: docker.eu1.hsdp.io/reporting/oauth2-proxy:${{ github.event.release.tag_name }}
