name: Scan

on:
  push:
    branches: 'edi-foundation-integration'

env:
  HSDP_DOCKER_HOST: docker.na1.hsdp.io

jobs:
  Init:
    runs-on: ubuntu-20.04
    container:
      image: docker.na1.hsdp.io/edi/build-env:master-45
      credentials:
        username: ${{ secrets.HSDP_DOCKER_USER }}
        password: ${{ secrets.HSDP_DOCKER_PASSWORD }}
    outputs:
      branchName: ${{ steps.branch.outputs.branch_name }}
      ciFullImageName: "${{ env.HSDP_DOCKER_HOST }}/edi/edi-foundation-oauth2-proxy:${{ steps.branch.outputs.branch_name }}-${{ github.run_number }}"
      rcFullImageName: "${{ env.HSDP_DOCKER_HOST }}/edi/edi-foundation-oauth2-proxy:${{ steps.branch.outputs.branch_name }}-${{ github.run_number }}-rc"

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        uses: vazco/github-actions-branch-name@v1
        id: branch

  Blackduck:
    needs: [Init]
    runs-on: builder_blr
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: blackduck scan
        run: powershell -ExecutionPolicy RemoteSigned -NoExit -File ${{ github.workspace }}\Build\PS\Invoke-BlackduckDetect.ps1 -SourcePath ${{ github.workspace }}

  Fortify:
    needs: [Init]
    runs-on: builder_blr
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Fortify scan
        run: powershell -ExecutionPolicy RemoteSigned -NoExit -File ${{ github.workspace }}\build\ps\Invoke-FortifyScan.ps1